import '../src/console/xml_arch.js';
import { startDecompilerLibrary } from '../src/console/libdecomp.js';
import { FunctionTestCollection } from '../src/console/testfunction.js';
import { StringWriter } from '../src/util/writer.js';
startDecompilerLibrary('/opt/ghidra');
const writer = new StringWriter();
const tc = new FunctionTestCollection(writer);
const testFile = process.argv[2] || 'ghidra-src/Ghidra/Features/Decompiler/src/decompile/datatests/concat.xml';
console.log('starting load of:', testFile);
console.time('load');
tc.loadTest(testFile);
console.timeEnd('load');
console.log('loaded, running tests');
console.time('run');
const failures: string[] = [];
tc.runTests(failures);
console.timeEnd('run');
console.log('done, failures:', failures.length);
console.log(writer.toString());
