/**
 * @file error.ts
 * @description Base error classes for the decompiler, translated from error.hh
 */

/**
 * The lowest level error generated by the decompiler.
 *
 * This is the base error for all exceptions thrown by the decompiler.
 * This underived form is thrown for very low level errors that immediately
 * abort decompilation (usually for just a single function).
 */
export class LowlevelError extends Error {
  /** Explanatory string */
  readonly explain: string;

  constructor(s: string) {
    super(s);
    this.name = 'LowlevelError';
    this.explain = s;
  }
}

/**
 * A generic recoverable error.
 *
 * This error is the most basic form of recoverable error, meaning there
 * is some problem that the user did not take into account.
 */
export class RecovError extends LowlevelError {
  constructor(s: string) {
    super(s);
    this.name = 'RecovError';
  }
}

/**
 * An error generated while parsing a command or language.
 *
 * This error is generated when parsing character data of some form,
 * as in a user command from the console or when parsing C syntax.
 */
export class ParseError extends LowlevelError {
  constructor(s: string) {
    super(s);
    this.name = 'ParseError';
  }
}

/**
 * An error from the XML/marshaling decoder.
 */
export class DecoderError extends LowlevelError {
  constructor(s: string) {
    super(s);
    this.name = 'DecoderError';
  }
}
